---
- name: remove prometheus exporters
  hosts: exporters
  become: true
  
  collections:
    - b4p.opentelemetry

  tasks:
    - include_role:
        name: node-exporter
        tasks_from: remove


