{
 "title": "System monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "process_owner",
    "label": "process_owner",
    "query": {
     "query": "label_values(process_cpu_time_seconds_total,process_owner)"
    }
   },
   {
    "name": "process_executable_name",
    "label": "process_executable_name",
    "query": {
     "query": "label_values(process_cpu_time_seconds_total{process_owner=~\"$process_owner\"},process_executable_name)"
    }
   },
   {
    "name": "disk_device",
    "label": "disk_device",
    "query": {
     "query": "label_values(system_disk_merged_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "system load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "system_cpu_load_average_1m{job=\"${job}\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "system_cpu_load_average_5m{job=\"${job}\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "system_cpu_load_average_15m{job=\"${job}\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "system cpu time by state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(system_cpu_time_seconds_total[1m])) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "system cpu time by state",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(system_cpu_time_seconds_total[1m])) by (state)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "top cpu time consuming processes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, (sum by(process_executable_name) (rate(process_cpu_time_seconds_total{state=\"system\",job=\"${job}\",process_owner=~\"${process_owner}\"}[5m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "top cpu time consuming users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, (sum by(process_owner) (rate(process_cpu_time_seconds_total{job=\"${job}\",process_executable_name=~\"${process_executable_name}\", process_owner=~\"${process_owner}\"}[1m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum of process cpu times per process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "(sum by(process_executable_name,state) (rate(process_cpu_time_seconds_total{job=\"${job}\",process_executable_name=~\"${process_executable_name}\",process_owner=~\"${process_owner}\"}[1m])) > 0) ",
     "legendFormat": "{{process_executable_name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Processes List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "processes",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max(process_cpu_time_seconds_total{process_owner=~\"${process_owner}\",process_executable_name=~\"${process_executable_name}\"}) by (process_command,process_executable_name,process_executable_path,process_owner,process_parent_pid,process_pid) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "system disk io time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(system_disk_io_time_seconds_total{job=\"${job}\",device=~\"${disk_device}\"}[1m])) by (device)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "system disk io bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(system_disk_io_bytes_total{job=\"${job}\",device=~\"${disk_device}\"}[1m])) by (device, direction)",
       "legendFormat": "{{device}}-{{direction}}"
      }
     ]
    },
    {
     "title": "system disk merged operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum(rate(system_disk_merged_total{device!~\"loop.*\",job=\"${job}\"}[1m])) by (device,direction)",
       "legendFormat": "{{device}}-{{direction}}"
      }
     ]
    },
    {
     "title": "system disk operations time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(system_disk_operation_time_seconds_total{job=\"${job}\",device!~\"loop.*\"}[1m])) by (device,direction)",
       "legendFormat": "{{device}}-{{direction}}"
      }
     ]
    }
   ]
  }
 ]
}